---

caddy_tls_providers:
  - provider: cloudflare
    challenge_type: dns
    provider_api_token: "{{ cloudflare_api_token }}"
    resolver_ip: 1.1.1.1

caddy_endpoints:
  - friendly_name: jellyfin
    fqdn: jf.amireally.online
    upstream: "ultima-thule:8096"
    tls_insecure: false
    tls_provider: cloudflare
  - friendly_name: audiobookshelf
    fqdn: abs.amireally.online
    upstream: "ultima-thule:30067"
    tls_insecure: false
    tls_provider: cloudflare
  - friendly_name: pocket-id
    fqdn: oidc.amireally.online
    upstream: "ultima-thule:30218"
    tls_insecure: false
    tls_provider: cloudflare
  - friendly_name: navidrome
    fqdn: nd.amireally.online
    upstream: "ultima-thule:4533"
    tls_insecure: false
    tls_provider: cloudflare

caddy_geoblock:
  db_path:
    - /usr/share/GeoIP/GeoLite2-Country.mmdb
  allow_countries:
    - US
    - CA
  blocked_status: 451
  blocked_message: "Access from your country is not allowed."