name: "Ansible Deploy"

on:
    workflow_dispatch:
    push:
      paths:
          - 'ansible/**'
      branches:
            - main
    workflow_run:
      # workflows: ["Oracle Cloud Terraform Apply","Digital Ocean Terraform Apply","Azure Terraform Apply"]
      workflows: ["Azure Terraform Apply"]
      types:
          - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
            
            - name: Set up Ansible
              run: |
                cd ansible && ansible-galaxy install -r requirements.yaml
              env:
                ANSIBLE_HOST_KEY_CHECKING: "False"
                ANSIBLE_CONFIG: ./ansible/ansible.cfg

            - name: Connect Tailscale
              uses: tailscale/github-action@v3
              with:
                oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
                oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
                tags: "tag:github"
                version: 1.86.2
            
            - name: Ansible Playbook
              run: |
                cd ansible && ansible-playbook -b run.yaml --limit caddy
              env:
                ANSIBLE_HOST_KEY_CHECKING: "False"
                ANSIBLE_CONFIG: ./ansible/ansible.cfg
                CF_TOKEN: ${{ secrets.CF_TOKEN }}